// Next
import Head from 'next/head'


// Components
import { CharCard } from '../components/CharCard'
import { CharGrid } from '../components/CharGrid'
import {EpisodesContainer} from '../components/EpisodesContainer'

// Types
import { ApiData, Character } from '../@types/Api'

// Styles
import * as S from '../styles/pages/home'
import { GlobalStyle } from '@/styles/globals'

interface Props {
  res: ApiData
}

interface CurrentInfo {
  count: number
  pages: number
  next: string | null
  prev: string | null
  current: string
}

interface Inputs {
  query: string
}


import { CharacterProvider } from '../contexts/CharacterContext'; 


export const API_URL = 'https://rickandmortyapi.com/api/character'

export default function Home() {
  return (
    <>
      <Head>
        <title>Rick and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CharacterProvider>
          <S.SplitScreenContainer>
            <CharGrid characterOrder={1} />
            <S.Divider />
            <CharGrid characterOrder={2} />
          </S.SplitScreenContainer>

        <EpisodesContainer/>
       

          <GlobalStyle/>
        </CharacterProvider>
      </main>
    </>
  )
}

// export async function getStaticProps() {
//   const res = await axios.get<ApiData>(API_URL).then(({ data }) => {
//     return data
//   })

//   return {
//     props: {
//       res,
//     },
//     revalidate: 60 * 60 * 2, // 2 hours,
//   }
// }
